# Application
spring.application.name=backend-engenheiro-senior
server.port=8080
server.servlet.context-path=/api

# Database (LOCAL)
spring.datasource.url=jdbc:postgresql://localhost:5432/appdb
spring.datasource.username=appuser
spring.datasource.password=apppass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# MinIO (LOCAL)
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=test-bucket
#minio.bucket-name=albuns

# JWT
#jwt.secret=seplagBackendSeniorSecretKey2026MatoGrossoProcessoSeletivoSimplificado
#jwt.secret=9a4f2c3d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9c0d1e2f
jwt.secret=testSecretKeyMuitoLongaParaFuncionarCorretamente123
jwt.expiration-minutes=60

# Rate Limit
rate.limit.capacity=10
rate.limit.refill-duration-minutes=1

# API Regionais
regionais.api.url=https://integrador-argus-api.geia.vip/v1/regionais
regionais.sync.cron=0 0 2 * * *

# Logging
logging.level.br.gov.mt.seplag=INFO
logging.level.org.springframework.security=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.diskspace.enabled=true
management.health.db.enabled=true

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Reduzir logs de debug do Spring Boot
logging.level.org.springframework.boot.autoconfigure=INFO
logging.level.org.springframework.boot.actuate.autoconfigure=INFO
logging.level.org.springframework.boot.test.autoconfigure=INFO

# Log apenas erros para testes
logging.level.root=ERROR
logging.level.br.mt.gov.seplag=INFO
